networks:
  webnet:
    driver: overlay
    attachable: true

services:
  app:
    build:
      context: .
    ports:
      - "4000:4000"
    env_file:
      - docker.env
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet

  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    networks:
      - webnet
